### ISSUE TITLE
Admin voting fail

### ISSUE THREAD

**Issue by ineiti** [c4dt/d-voting#138]
If you do the following, the page crashes, but nothing shows:

- login as admin
- open a form you're not allowed to vote in
- click on "vote"
- page crashes

So the "vote" button should only be shown to ids with voting rights, not all admins.

**Comment by PascalinDe** [comment]
Cannot reproduce the visibility of the "Vote" button to non-voter admins:

* non-owner, non-voter admin view of an open form:
![Screenshot 2024-03-07 at 10-21-59 D-Voting](https://github.com/c4dt/d-voting/assets/15922677/30909c7c-4d27-4ff9-aabe-9d49d7281d6c)


* owner, non-voter admin view of an open form:

![Screenshot 2024-03-07 at 10-24-18 D-Voting](https://github.com/c4dt/d-voting/assets/15922677/15b1c67d-c1d0-435d-80b2-f042ce2dcec4)

* voting view of authenticated non-voter:

![Screenshot 2024-03-07 at 10-26-58 D-Voting](https://github.com/c4dt/d-voting/assets/15922677/ddd1df7d-55bc-4f6d-a660-b42c0e1c4c33)

**Comment by PascalinDe** [comment]
cannot reproduce on demo either:

* non-voter admin

![Screenshot 2024-03-07 at 11-05-21 D-Voting](https://github.com/c4dt/d-voting/assets/15922677/c76192e4-eec4-4ab0-bfa2-e62933327158)

**Comment by ineiti** [comment]
https://xkcd.com/583/
