### ISSUE TITLE
Cannot add 5'000 scipers for an election

### ISSUE THREAD

**Issue by dragonleman** [c4dt/d-voting#155]
When I add 5'000 scipers as voters, I get : 

![image](https://github.com/c4dt/d-voting/assets/25434152/6f6d613f-5860-4033-9c9b-36a6f28ddcb7)

The election is created but I cannot do anything : 

![image](https://github.com/c4dt/d-voting/assets/25434152/7ab9b6b2-fb5a-483c-97bb-45cd01652a64)

And I don't see anymore the button "Create form" (as I am not anymore an admin). But if I refresh the page, I can get back the button "Create form" ...

If I put my sciper number at the top of the list of the scipers number, I can vote even with the error message above. But if my sciper number is at the bottom of the list of the scipers number, I am not allowed to vote ... 

> [!NOTE]
> It seems I can add batches of 300 to 500 (max) sciper numbers. 
> It would be useful to know how many sciper numbers have been added. The window of "Adding voters" keeps growing too much with a large number of scipers. A vertical scroll woulb be enough.

**Comment by multiscan** [comment]
Digging a bit further I saw that while adding the voters, the browser does one POST request per sciper number and the requests seams to fail randomly (see attached images). The error message is "Unauthorized - only admins allowed".
In fact, what happens is that the when authorisation is checked, the `authEnforcer` is not ready yet. I think adding an `await` in front of line 7 of `users.ts` should fix the issue.

<img width="367" alt="Screenshot 2024-04-11 at 10 38 42" src="https://github.com/c4dt/d-voting/assets/12849/b29f0928-5843-49ac-8907-96c067d0637d">
