### ISSUE TITLE
Hide useless informations to users

### ISSUE THREAD

**Issue by dragonleman** [c4dt/d-voting#156]
When a user access to the election form, he can see (here you see the admin mode, because "Actions" are full displayed, but the user can see the other stuffs) :

![image](https://github.com/c4dt/d-voting/assets/25434152/f1abc7ad-791f-4ccf-8887-cb1452147035)

I suggest to remove informations that only admin can watch, as : 
- Status
- DKG Statuses
- User ID of voters (just let him see : number of ballot cast, and his sciper ID, so he can see if he has already submitted his vote).

**Comment by PascalinDe** [comment]
I'll have a look

from what I saw when I looked into the buttons, not all of these elements will be equally easy to show/hide, so I'd propose the following order of importance:

* [ ] only show the user ID of the logged-in user
* [ ] don't show the DKG statuses
* [ ] don't show the form statuses

I'll start working on it now

**Comment by PascalinDe** [comment]
quick question, for the non-admin view, the status view is this

![Screenshot 2024-04-16 at 13-30-28 D-Voting](https://github.com/c4dt/d-voting/assets/15922677/42e6a58b-ee81-4a98-b088-2a40dd732e2d)

i.e. no "Nodes initialiazed"/"Setup" status - I think it is useful for the user to know whether the form is open/closed or the results are available, so should I just remove the "Ballots shuffled"/"Ballots decrypted" parts?

**Comment by dragonleman** [comment]
I think the easiest way to do, from the "Forms" page (where the forms are listed). disable the click on the election (column on the left : "Form title"). Only owner and admin can click.

**Comment by PascalinDe** [comment]
sounds good, the view will then be completely disabled (i.e. a non-admin user will get a 401)

**Comment by PascalinDe** [comment]
fait
