### ISSUE TITLE
Remove the port from the https-scheme for the dela-public URL

### ISSUE THREAD

**Issue by ineiti** [c4dt/d-voting#29]
Some thoughts on the dela public URL:
1. it's somewhat confusing to have `https` for the scheme if the dela node port is TLS terminated by a reverse proxy - what would be better? Also think that currently `grpcs` points to a self-signed TLS terminated dela node
2. the scheme `https` needs to take a `443` port, which looks ugly and is confusing. Either we find another scheme name for this case, or remove the need for the `443` port in `https`. Even if there is a little possibility of confusion.

@lanterno @PascalinDe what do you think?

**Comment by PascalinDe** [comment]
is this still relevant in light of the developments around TLS?

**Comment by ineiti** [comment]
As far as I can tell it's still an issue in the `minogrpc` network layer. But I think we can close it by saying that the next network layer will be `minows` anyway, so this is not a problem anymore.
