### ISSUE TITLE
add EPFL CSS

### ISSUE THREAD

**Issue by PascalinDe** [c4dt/d-voting#42]
for the production version, we need a CSS following the EPFL's style guidelines

**Comment by dragonleman** [comment]
At least, the brand identity is compulsory : 

https://epfl-si.github.io/elements/#/

**Comment by lanterno** [comment]
I added the EPFL logo, but the font "Arial", I'm not sure what we need to add more than that. 

Looking at the brand Identity here, those two things seem to be the main requirements. 

@dragonleman Do you see something else we need to add? (the [web page](https://epfl-si.github.io/elements/#/) wasn't very clear)

**Comment by dragonleman** [comment]
@lanterno : 

EPFL logo and Arial font are basically the main parts for the EPFL brand identity. I would add the [breadcrump](https://epfl-si.github.io/elements/#/molecules/breadcrumb), per example : "EPFL > School Assembly Election" or "EPFL > Postdoctoral courses elections"  ... 

Components, like [checkboxes](https://epfl-si.github.io/elements/#/atoms/checkbox), [lists](https://epfl-si.github.io/elements/#/atoms/list), [buttons](https://epfl-si.github.io/elements/#/atoms/button), [alerts](https://epfl-si.github.io/elements/#/atoms/alert), [anchors/links](https://epfl-si.github.io/elements/#/atoms/link), etc. could not follow the EPFL guidelines at the moment. But for the next versions they should be gradually added.

**Comment by PascalinDe** [comment]
@lanterno I took over the ticket
