### ISSUE TITLE
Display of the footer of a form

### ISSUE THREAD

**Issue by dragonleman** [c4dt/d-voting#46]
In each form, a footer is needed with those information: 
- footer text
- contact title
- contact phone
- contact email

Ex. (for the Assemblée de l'Ecole votations) : 
footer text -> EPFL
contact title -> Secrétariat AE
contact phone -> +41 (0)21 693 69 16
contact email -> secr.assemblee.ecole@epfl.ch

**Comment by dragonleman** [comment]
> @dragonleman the content of the footer must depend on the election?

In the footer, only those 4 information are needed for each election.

**Comment by PascalinDe** [comment]
we decided to use an additional information field instead #141
