### ISSUE TITLE
Requirements for voting system

### ISSUE THREAD

**Issue by ineiti** [c4dt/d-voting#47]
Forms: 24
Voters: 10'000
Min. choices: 0
Max. choices: 5
Candidates: 20
Actual ballots: 500 - 1'000

**Comment by PascalinDe** [comment]
to close this ticket, please add a document w/ that information in the repository

**Comment by PascalinDe** [comment]
@ineiti could you add a line with your current benchmarks in the README? that would close this ticket

**Comment by ineiti** [comment]
State of 2024-03-07:

# Benchmarks

On 7th of March 2024, we ran a benchmark on the following system:
- 1 node on a server in EPFL
- 3 nodes on one server in switch-engines/ZH
- a client form a DSL home account

## 1'000 votes

- casting 1000 votes took 16.02.20 (298) - 16.00.45 (119)
  - 95 seconds -> 95ms / vote 
  - 179 blocks -> 5.6 votes / block
- closing: immediate
- shuffle: 16.11.45 (308) - 16.10.49 (299)
  - 56 seconds
  - 9 blocks
  - Timeout error in frontend
- decrypting: 16.13.13 (308) - 16.13.18 (310)
  - 5 seconds
  - 2 blocks
  - nonce error in the backend
- combining
  - 1 second
  - 1 block

## 10'000 votes

4 minutes outage because the main node failed
Running over CISCO / EPFL

- casting 10'000 votes took 16.37.36 (1779) - 16.17.49 (313)
- `time` on 9392 votes = 14m48s
  - 888s / 9392 votes -> 95ms / vote
  - 10000 votes / 1466 blocks -> 6.8 votes/blocks
- closing: 2s - 1 block
- shuffle: 16.51.22 (1790) - 16.42.20 (1780)
  - Timout error in frontend
  - 9m2s
  - 10 blocks
- decrypting 17.07.20 (1793) - 17.06.31 (1790)
  - 49s
  - 3 blocks
- combining: 17.08.59 (1794) - 17.08.12 (1793)
  - 47s
  - 1 block
