### ISSUE TITLE
Summary of current test-run

### ISSUE THREAD

**Issue by ineiti** [c4dt/d-voting#52]
I'm using the benchmark `BenchmarkIntegration_CustomVotesScenario` in [performance_test.go](../tree/main/integration/performance_test.go) to test how much we need to speed things up. Here some preliminary results and thoughts:

- According to [state_of_smart_contract.md](../tree/main/docs/state_of_smart_contract.md), there is only a single instance of any smart contract. So:
  - it will get slower the more elections are stored
  - the proxy will probably have to handle this and return only appropriate data structures
- on my macbook I can get about 200 ballots stored, shuffled, and decrypted. More than that fails in the shuffling
- just casting ballots shows a big slowdown: the 100th ballot takes 0.7s, the 200th 1.2s, the 300th 1.7s, the 400th 2.3s, the 999th 5.4s, so an increase in casting a new ballot of 0.5s per 100 existing ballots
- The 100th ballot with 3 nodes takes 650ms, with 7 nodes it takes 720ms, so there is no big increase when the number of nodes increases

Probable issues to open (waiting on some more investigations):
- speed up casting a ballot by a factor of 100: it should be below 1s for 5 elections and 10'000 votes each. -> #53 
- make shuffling work with 1'000 and 10'000 ballots
- make sure the smart contract is smart enough that the proxy can correctly extract the different elections
- verify the decryption is actually stored, too, and possibly even the results. Else it will take clients a lot of time to calculate the results

Once this works, the next steps are:
- test all of this from the client side
- using a real network with network delays

**Comment by PascalinDe** [comment]
closing this issue to clean up issues for transfer
