### ISSUE TITLE
Reducing time to cast a ballot

### ISSUE THREAD

**Issue by ineiti** [c4dt/d-voting#53]
Currently casting the 1000th ballot takes about 5.5s. This must be reduced to
- at maximum 5 elections * 1000 ballots with 1s to cast a ballot: 200ms
- in the best case 1s to cast a ballot with 5 elections * 10'000 ballots: 20ms

After many measurements, the main bottlenecks are:
- Syncing - which sends the whole chain to all the nodes after every block - #54 
  - If no syncing necessary, reduces the time for the 1000th ballot to 600ms 
- (De)serializing of the election data - #55
  - If it is cut by 10, 1000th ballot will take 60ms
- The leader executing the `CastVote` contract twice - #56
  - The 1000th ballot will take 40ms

And, finally, test it all... #125 

Of course this all needs to be verified on a more realistic network, too, and from the client's point of view.

**Comment by PascalinDe** [comment]
is this still an issue?

**Comment by ineiti** [comment]
Implemented, tested in EPFL elections in 2024, all good...
