### ISSUE TITLE
Making (De)serializing the election contract faster

### ISSUE THREAD

**Issue by ineiti** [c4dt/d-voting#55]
To add a new ballot, the election contract Deserializes a complete form, adds the ballot, and Serializes the form again. This is very expensive and should be changed.

Some ideas:
- store the ballots in blocks of 100 ballots (to be configured)
- the form only has pointers to these blocks, or a counter to the blocks, if we store them at `Hash(formID | block-#)`
- but then the shuffle and decryption code needs to be adjusted

**Comment by PascalinDe** [comment]
this has been resolved, no?

**Comment by ineiti** [comment]
Implemented.
