### ISSUE TITLE
Non-owner can add voters to form of other user

### ISSUE THREAD

**Issue by PascalinDe** [c4dt/d-voting#81]
While a non-owner cannot manage other aspects of a form (opening, closing, deleting, ...), they can add voters to the form. Following the logic of not giving them the right to manage the form, they should also not be able to add voters.

@dragonleman @multiscan : unless this is explicitely desired behaviour?

**Comment by dragonleman** [comment]
For a form :
- the owner can manage and add voters
- a non-owner cannot access the management of the form and therefore cannot add voters

**Comment by PascalinDe** [comment]
> For a form :
> 
>     * the owner can manage and add voters
> 
>     * a non-owner cannot access the management of the form and therefore cannot add voters

OK, thanks for confirming, we will fix this then
