### ISSUE TITLE
set up dev environment

### ISSUE THREAD

**Issue by PascalinDe** [c4dt/d-voting#86]
set up the project:

* [x] create a fork of c4dt/d-voting
* [x] add me as a maintainer
* [x] set up either the local or the dockerized environment
* [x] confirm that the project is set up correctly by creating a new form, adding yourself as voter, vote, close the form and display the results
* [x] document any problems in form of issues in this project
* [x] if any set up step was not clear, add a PR w/ updates to the documentation

**Comment by MaximeZmt** [comment]
(spent roughly 6h30)
