### ISSUE TITLE
set up the project management

### ISSUE THREAD

**Issue by PascalinDe** [c4dt/d-voting#87]
* [x] (briefly) outline the project's requirements
* [x] create an "epic" ticket with the outline
* [x] create smaller tickets for each step in the project, and link them to the epic ticket
* [x] for each of the smaller tickets, add an estimate of the time you'll spend on it

**Some pointers**

* don't forget to add tickets like "read the docs", ... - they don't produce code, but take up time as well!
* the estimates are **not** in any way taken into account for grading, nor is it a problem if your estimates are off - this exercise is purely for you to learn creating a time budget
* please add the "student project" label to all of your tickets
* please add the tickets to the "Student Project Spring '24 [...]" project
* you're free in the form/content of your tickets, but keep in mind that I'll read them too - I can help you better if you put all the necessary information in there

**Comment by MaximeZmt** [comment]
(spent roughly 7h)
