### ISSUE TITLE
TestCrash fails sometimes

### ISSUE THREAD

**Issue by ineiti** [c4dt/d-voting#90]
The TestCrash in `./integration/integration_test.go:24` fails sometimes on line 298 when verifying the call to `decryptBallots` because the previous transactions have not been correctly included.
This has mostly been fixed by allowing the `pool.Add` to fail in `txManager.addAndWait` in `./integration/transaction.go:117`, but might pop up here and there again.

Another failure is in line 288, the call `waitForStatus(types.PubSharesSubmitted, ...)` fails with `already made a submission`. But this is much more rare and has not been invested into yet.

**Comment by PascalinDe** [comment]
can this be closed as the related PR has been merged?
